project_id = "nufksbhydjhqaqqfxkdp"

[functions.generate-extension]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.agent-pipeline]
verify_jwt = false

[functions.discover-trends]
verify_jwt = false