import { useEffect, useState, useCallback } from "react";
import Editor from "@monaco-editor/react";
import { Code2, Download, RotateCcw, Save, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import JSZip from "jszip";
import { saveAs } from "file-saver";
import type { ExtensionSpec } from "@/lib/generate-extension";
import { generateAllFiles, type GeneratedFiles } from "@/lib/generate-extension";
import { generateExtensionIcons } from "@/lib/generate-icons";
import { useAuth } from "@/hooks/use-auth";
import { persistProject } from "@/lib/project-persist";

const fileIcons: Record<string, string> = {
  "manifest.json": "📋",
  "popup.html": "🖼️",
  "popup.js": "⚡",
  "popup.css": "🎨",
  "background.js": "⚙️",
  "content.js": "📄",
  "styles.css": "🎨",
  "options.html": "⚙️",
  "options.js": "🔧",
  "utils/api.js": "🔌",
  "utils/storage.js": "💾",
};

function getLanguage(filename: string) {
  if (filename.endsWith(".json")) return "json";
  if (filename.endsWith(".html")) return "html";
  if (filename.endsWith(".css")) return "css";
  return "javascript";
}

export default function CodeEditorPage() {
  const [files, setFiles] = useState<GeneratedFiles>({});
  const [activeFile, setActiveFile] = useState("manifest.json");
  const [specName, setSpecName] = useState("extension");

  useEffect(() => {
    // Try AI-generated files first, then fallback to template
    const storedFiles = sessionStorage.getItem("extension-files");
    const storedSpec = sessionStorage.getItem("extension-spec");

    if (storedFiles) {
      try {
        const parsed = JSON.parse(storedFiles);
        setFiles(parsed);
        const keys = Object.keys(parsed);
        if (keys.includes("manifest.json")) setActiveFile("manifest.json");
        else if (keys.length > 0) setActiveFile(keys[0]);
      } catch { /* fallthrough */ }
    } else if (storedSpec) {
      try {
        const spec: ExtensionSpec = JSON.parse(storedSpec);
        setFiles(generateAllFiles(spec));
      } catch { /* ignore */ }
    }

    if (!storedFiles && !storedSpec) {
      const demoSpec: ExtensionSpec = {
        name: "My Extension",
        description: "A Chrome extension generated by Extension Forge AI",
        features: ["Feature 1", "Feature 2"],
        permissions: ["activeTab", "storage"],
        hostPermissions: ["https://*/*"],
        apis: [],
      };
      setFiles(generateAllFiles(demoSpec));
    }

    if (storedSpec) {
      try {
        setSpecName(JSON.parse(storedSpec).name?.toLowerCase().replace(/\s+/g, "-") || "extension");
      } catch {}
    }
  }, []);

  const updateFile = useCallback((value: string | undefined) => {
    if (value !== undefined) {
      setFiles(prev => ({ ...prev, [activeFile]: value }));
    }
  }, [activeFile]);

  const handleDownloadZip = async () => {
    const zip = new JSZip();
    Object.entries(files).forEach(([name, content]) => {
      if (name.includes("/")) {
        const parts = name.split("/");
        const folder = zip.folder(parts[0]);
        folder?.file(parts.slice(1).join("/"), content);
      } else {
        zip.file(name, content);
      }
    });
    const icons = generateExtensionIcons();
    const iconsFolder = zip.folder("icons")!;
    iconsFolder.file("icon16.png", icons["icons/icon16.png"]);
    iconsFolder.file("icon48.png", icons["icons/icon48.png"]);
    iconsFolder.file("icon128.png", icons["icons/icon128.png"]);
    const blob = await zip.generateAsync({ type: "blob" });
    saveAs(blob, `${specName}.zip`);
    toast.success("Extension package downloaded!");
  };

  const handleRegenerate = () => {
    const storedSpec = sessionStorage.getItem("extension-spec");
    if (storedSpec) {
      const spec = JSON.parse(storedSpec);
      setFiles(generateAllFiles(spec));
      toast.success("Files regenerated from template");
    }
  };

  const fileList = Object.keys(files);
  const totalLines = Object.values(files).reduce((acc, f) => acc + f.split("\n").length, 0);

  return (
    <div className="flex flex-col h-[calc(100vh-3rem)]">
      <div className="flex items-center justify-between px-4 py-2 border-b border-border shrink-0">
        <div className="flex items-center gap-3">
          <Code2 className="h-5 w-5 text-primary" />
          <h1 className="font-semibold">Code Editor</h1>
          <Badge variant="secondary" className="font-mono text-[10px]">{fileList.length} files</Badge>
          <Badge variant="secondary" className="font-mono text-[10px]">{totalLines} lines</Badge>
        </div>
        <div className="flex gap-2">
          <Button onClick={handleRegenerate} size="sm" variant="outline">
            <RotateCcw className="h-3.5 w-3.5 mr-1.5" /> Reset
          </Button>
          <Button onClick={handleDownloadZip} size="sm" className="bg-gradient-cyber text-primary-foreground">
            <Download className="h-3.5 w-3.5 mr-1.5" /> Download .zip
          </Button>
        </div>
      </div>

      <div className="flex flex-1 min-h-0">
        <div className="w-56 border-r border-border bg-card p-2 overflow-y-auto shrink-0">
          <p className="text-xs text-muted-foreground font-semibold uppercase px-2 py-1 mb-1">Extension Files</p>
          {fileList.map(name => (
            <button
              key={name}
              onClick={() => setActiveFile(name)}
              className={`w-full text-left px-3 py-1.5 rounded-md text-sm flex items-center gap-2 transition-colors ${
                activeFile === name ? "bg-primary/10 text-primary" : "text-muted-foreground hover:bg-secondary"
              }`}
            >
              <span className="text-xs">{fileIcons[name] || "📄"}</span>
              <span className="font-mono text-xs truncate">{name}</span>
            </button>
          ))}
        </div>

        <div className="flex-1 min-w-0">
          <Editor
            height="100%"
            language={getLanguage(activeFile)}
            value={files[activeFile] || ""}
            onChange={updateFile}
            theme="vs-dark"
            options={{
              fontSize: 13,
              fontFamily: "'JetBrains Mono', monospace",
              minimap: { enabled: false },
              padding: { top: 16 },
              scrollBeyondLastLine: false,
              wordWrap: "on",
            }}
          />
        </div>
      </div>
    </div>
  );
}
