import { useEffect, useState, useCallback } from "react";
import { motion } from "framer-motion";
import Editor from "@monaco-editor/react";
import { Code2, FileCode, Download, Package as PkgIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import JSZip from "jszip";
import { saveAs } from "file-saver";
import type { ExtensionSpec } from "@/lib/generate-extension";
import { generateAllFiles, type GeneratedFiles } from "@/lib/generate-extension";

const fileIcons: Record<string, string> = {
  "manifest.json": "📋",
  "popup.html": "🖼️",
  "popup.js": "⚡",
  "background.js": "⚙️",
  "content.js": "📄",
  "styles.css": "🎨",
  "options.html": "⚙️",
  "options.js": "🔧",
};

function getLanguage(filename: string) {
  if (filename.endsWith(".json")) return "json";
  if (filename.endsWith(".html")) return "html";
  if (filename.endsWith(".css")) return "css";
  return "javascript";
}

export default function CodeEditorPage() {
  const [files, setFiles] = useState<GeneratedFiles>({});
  const [activeFile, setActiveFile] = useState("manifest.json");
  const [hasSpec, setHasSpec] = useState(false);

  useEffect(() => {
    const stored = sessionStorage.getItem("extension-spec");
    if (stored) {
      try {
        const spec: ExtensionSpec = JSON.parse(stored);
        setFiles(generateAllFiles(spec));
        setHasSpec(true);
      } catch { /* ignore */ }
    }
    if (!stored) {
      // Generate a default demo
      const demoSpec: ExtensionSpec = {
        name: "My Extension",
        description: "A Chrome extension generated by Extension Forge AI",
        features: ["Feature 1", "Feature 2"],
        permissions: ["activeTab", "storage"],
        hostPermissions: ["https://*/*"],
        apis: [],
      };
      setFiles(generateAllFiles(demoSpec));
    }
  }, []);

  const updateFile = useCallback((value: string | undefined) => {
    if (value !== undefined) {
      setFiles((prev) => ({ ...prev, [activeFile]: value }));
    }
  }, [activeFile]);

  const handleDownloadZip = async () => {
    const zip = new JSZip();
    Object.entries(files).forEach(([name, content]) => {
      zip.file(name, content);
    });
    zip.folder("icons");
    const blob = await zip.generateAsync({ type: "blob" });
    const specName = sessionStorage.getItem("extension-spec");
    let zipName = "extension";
    if (specName) {
      try { zipName = JSON.parse(specName).name.toLowerCase().replace(/\s+/g, "-"); } catch {}
    }
    saveAs(blob, `${zipName}.zip`);
    toast.success("Extension package downloaded!");
  };

  const fileList = Object.keys(files);

  return (
    <div className="flex flex-col h-[calc(100vh-3rem)]">
      <div className="flex items-center justify-between px-4 py-2 border-b border-border shrink-0">
        <div className="flex items-center gap-2">
          <Code2 className="h-5 w-5 text-primary" />
          <h1 className="font-semibold">Code Editor</h1>
        </div>
        <Button onClick={handleDownloadZip} size="sm" className="bg-gradient-cyber text-primary-foreground">
          <Download className="h-4 w-4 mr-2" /> Download .zip
        </Button>
      </div>

      <div className="flex flex-1 min-h-0">
        {/* File tree */}
        <div className="w-56 border-r border-border bg-card p-2 overflow-y-auto shrink-0">
          <p className="text-xs text-muted-foreground font-semibold uppercase px-2 py-1 mb-1">Files</p>
          {fileList.map((name) => (
            <button
              key={name}
              onClick={() => setActiveFile(name)}
              className={`w-full text-left px-3 py-1.5 rounded-md text-sm flex items-center gap-2 transition-colors ${
                activeFile === name ? "bg-primary/10 text-primary" : "text-muted-foreground hover:bg-secondary"
              }`}
            >
              <span>{fileIcons[name] || "📄"}</span>
              <span className="font-mono text-xs truncate">{name}</span>
            </button>
          ))}
        </div>

        {/* Editor */}
        <div className="flex-1 min-w-0">
          <Editor
            height="100%"
            language={getLanguage(activeFile)}
            value={files[activeFile] || ""}
            onChange={updateFile}
            theme="vs-dark"
            options={{
              fontSize: 13,
              fontFamily: "'JetBrains Mono', monospace",
              minimap: { enabled: false },
              padding: { top: 16 },
              scrollBeyondLastLine: false,
              wordWrap: "on",
            }}
          />
        </div>
      </div>
    </div>
  );
}
